
import { Component } from '@angular/core';
import { Router } from '@angular/router';




@Component({
  selector: 'app-head',
  template: `
  <mat-toolbar color="Primary" class="mat">
  <a href="http://localhost:4200/products"style="color:pink;"><span class="gatito">Kimetsu's Shop</span></a>
<app-cart [routerLink]="['/checkout']"(click)="goToCheckout"></app-cart>
</mat-toolbar>
  `,
  styleUrls:['./head.component.css']

})
export class HeadComponent {

  constructor(private Router: Router) {
  }
  
  goToCheckout(): void {
    this.Router.navigate(['/checkout']);
  }


}


/*ANGULAR FUNCIONA DE TAL MANERA QUE CADA COMPONENTE SE PUEDA COMUNICAR>
LAS RUTAS SE PUEDAN GENERAR RUTS Y SUBRUTAS DE TAL MANERA QUE NO TENGN QUE DEPENDER DEL 
MODULO GENERAL APP_ COMPONENT > EXISTEN DIRECTIVAS QUE SON NG FOR NG IF NG SWITCH Y OTRAS 
DIRECTIVAS MAS. LAS CUALES SON LITERALMENTE MANERAS DE CREARCODIGO ENLAZANDO EL HTML, 
LA INTERPOLACION DE DATOS ES LA TRANSFORMACION DE LA INFORMACION DESDE UN PUNTO A OTRO
CAMBIANDO ASI EL ESTADO O ENVIANDO A RECIBIR UN DATO.
LOS DECORADORES, MARCAN EL COMPORTAMIENTO DE UNA CLASE Y CUAL SERA SU FUNCION DURANTE EL SELECTOR EN ESTE 
CASO LA APP- HEAD Y EN ESTE CASO NO SE HACE USO DE UN TEMPLATEURL PARA LEER EL COMPONENTE DEL HTML 
EL CUAL  NO EXISTE UN FICHERO COMO TAL DEL CART COMPONENT, HE APRENDIDO COMO SE COMUNICAN
COMPONENTES Y COMO FUNCIONA UNA ESTRUCTURA DEUN PROYECTO DE ANGULAR. HE APRENDIDO DE INTERFACES
Y HE APRENDIDO DE SERVICIOS, HE VISTOPOR ENCIMITA ACERCADE APIS DE MANERA CORTA. YA PUEDO HACER
VARIOS MENUS Y HACER RUTAS CORRESPONDIENTEMETE, FALTA APRENDER EL ENVIO DE INFORMACION DE UNA MANERA
MAS LEGIBLE ENTENDIENDO SU CORRECTO FUNCIONAMIENTO, SE QUE LOS SERVICIOS SON SERVICIOS HTTP QUE CONSUMEN
CIERTO TIPO DE INFORMACION DE LA API Y SE QUE CADA VEZ QUE NECESITO DE UTILIZAR ALGUNA LIBRERIA 
SEA ANGULAR MATERIAL SEA BOOTSTRAP O SEA CUALQUIER OTRO TIPO SIMILAR NECESITO REFERENCIAR DICHA INFORMACION
EN LOS MODULOS DONDE SE ENCUENTRE EL PROYECTO DE MANERA GLOBAL. PARA ASI APLICAR DICHOS ESTILOS AL PROYECTO
SE QUE EN LOS ASSETS PUEDO PONER TODAS MIS IMAGENES ASI COMO FUENTES DENTRO DE ESA CARPETA */